---
title: "stickleback_script_june_7_2025"
author: "Zoe Mozola"
date: "2025-06-07"
output: html_document
---
#Setup
##Packages and WD
```{r Setup}
#Set Working Directory IN CONSOLE
#setwd("C:/Users/zoemo/OneDrive/Documents/GitHub/Threatened-Stickleback")


#Remove list = list() ?????
rm(list=ls())

pacman::p_load(tidyverse, here, janitor, ggplot2, ggsignif, ggpubr)


#Old way of doing it maybe not necessary?
library(tidyverse)
library(here)
library(janitor)
library(ggplot2)
library(ggsignif)
library(ggpubr)



#=======
#>>>>>>> 9c0dbe4f94e1273edd5b1255049a99e60bd6020f
```


##Read-In
```{r Read-In}
#data1 <- read_csv("C:/Users/zoemo/OneDrive/Documents/GitHub/Threatened-Stickleback/Data/ZM Data Sheet Cleaned Reduced.csv")

#data1 <- read_csv("../Data/ZM Data Sheet Cleaned Reduced.csv")

data2 <- read_csv(here("Data", "ZM Data Sheet Extra Measurements.csv"))

data3 <- read_csv(here("Data", "ZM Data Sheet Outliers Removed Sep 20 2025.csv"))

```

##Cleaning
```{r Cleaning}
# Set Current dataset 
#data <- data2 #Outliers in
data <- data3 #Outliers removed


#Encleanenate
dataclean <- data %>%
  clean_names() %>%
  filter(!is.na(fish_id)) %>%
  #Make tag for time period
  mutate(time_period = ifelse(year >= 2000, "Present", "Historical")) %>%
  #Make tag for unarmoured/giant
  mutate(type = ifelse(body_of_water %in% c("Drizzle Lake", "Mayer Lake"), "Giant", "Unarmoured")) %>%
  #Make Plate Arrangement a string
  mutate(plate_l_combined = as.factor(plate_l_combined)) %>%
  mutate(plate_r_combined = as.factor(plate_r_combined)) %>%
  mutate(body_of_water = factor(body_of_water, levels = c("Mayer Lake", "Drizzle Lake",
                                            "Serendipity Lake", "Boulton Lake", 
                                            "Rouge Lake")))



#Make Boulton
boulton <- dataclean %>%
  filter(body_of_water=="Boulton Lake")
  

#Make Drizzle
drizzle <- dataclean %>%
  filter(body_of_water=="Drizzle Lake")

#Make Mayer
mayer <- dataclean %>%
  filter(body_of_water=="Mayer Lake")

#Make Serendipity
serendipity <- dataclean %>%
  filter(body_of_water=="Serendipity Lake")

#Make Rouge
rouge <- dataclean %>%
  filter(body_of_water=="Rouge Lake")







#Make it sexy
sexy <- dataclean %>%
  filter(sex %in% c("M", "F"))

#Make Boulton
boultonsex <- sexy %>%
  filter(body_of_water=="Boulton Lake")

#Make Drizzle
drizzlesex <- sexy %>%
  filter(body_of_water=="Drizzle Lake")

#Make Mayer
mayersex <- sexy %>%
  filter(body_of_water=="Mayer Lake")

#Make Serendipity
serendipitysex <- sexy %>%
  filter(body_of_water=="Serendipity Lake")

#Make Rouge
rougesex <- sexy %>%
  filter(body_of_water=="Rouge Lake")

```




##Formula Setup
```{r Formula Setup}

#Make lists for for loops

numeric_traits <- c("sl", "body_depth.adj", "ap_length.adj", "ap_width.adj", "jaw_length.adj", 
                    "ppl.adj", "ppw.adj", "dorsal_1.adj", "dorsal_2.adj", "dorsal_3.adj", 
                    "pelvic_spine.adj", "eye_diameter.adj", "plate_l_total", "plate_r_total")

numeric_traits_noadj <- c("sl", "body_depth", "ap_length", "ap_width", "jaw_length", 
                    "ppl", "ppw", "dorsal_1", "dorsal_2", "dorsal_3", "pelvic_spine", 
                    "eye_diameter")

numeric_traits_nosl <- c("body_depth.adj", "ap_length.adj", "ap_width.adj", "jaw_length.adj", 
                    "ppl.adj", "ppw.adj", "dorsal_1.adj", "dorsal_2.adj", "dorsal_3.adj",
                   "pelvic_spine.adj", "eye_diameter.adj", "plate_l_total", "plate_r_total")

countable_traits <- c("ap_pa", "pp_pa", "dorsal_1_pa", "dorsal_2_pa", "dorsal_3_pa", "pelvic_spine_pa")

lakes <- list("Drizzle Lake" = drizzle, "Mayer Lake" = mayer, "Serendipity Lake" = serendipity, "Boulton Lake" = boulton, "Rouge Lake" = rouge)

lakes2 <- list("drizzle" = drizzle, "mayer" = mayer, "serendipity" = serendipity, "boulton" = boulton, "rouge" = rouge)

lakes3 <- c("Drizzle Lake", "Mayer Lake", "Serendipity Lake", "Boulton Lake", "Rouge Lake")

sexylakes <- list("Drizzle Lake" = drizzlesex, "Mayer Lake" = mayersex, "Serendipity Lake" = serendipitysex, "Boulton Lake" = boultonsex, "Rouge Lake" = rougesex)
#Note, I just realized I could do this the other way with filtering within the loop

lakecolours <- c("Drizzle Lake" = "chartreuse4", "Mayer Lake" = "darkorange2", "Serendipity Lake" = "blue", "Boulton Lake" = "purple", "Rouge Lake" = "red")

platetotals <- c("Left" = "plate_l_total", "Right" = "plate_r_total", "Both Combined" = "plate_lr_total")

platearrangements <- c("Left" = "plate_l_combined", "Right" = "plate_r_combined")

timeperiods <- c("Historical", "Present")

sex <- c("M", "F")

presabscolours <- list("N" = "indianred", "Y" = "olivedrab4")

```


##Allometric Adjustments by Lake
```{r Allometric Adjustments by Lake}

#ALLOMETRIC ADJUSTMENTS

#SOMETHING IS BAD AND WRONG HERE, the code loops fine but I have somehow effed up the allometric adjustment

#Create list to store adjusted dfs
adjusted_lakes <- list()

for (j in names(lakes2)) {
  lake_data <- lakes2[[j]]
  for (i in numeric_traits_noadj) {
    #Log transform all numerical traits in separate column
    log_col <- paste0(i, ".log")
    lake_data[[log_col]] <- log10(lake_data[[i]])
    
    #Fit ANOVA with logged traits
    model <- lm(as.formula(paste(log_col, "~ sl")), data = lake_data) 
    #took out by body of water since doing by water body already? Not sure if this is right
    #Problem here??
    slope <- model$coefficients["sl"]
    
    #Compute size-adjusted trait
    adj_col <- paste0(i, ".adj")
    lake_data[[adj_col]] <- lake_data[[log_col]] * (mean(lake_data$sl) / lake_data$sl)^slope
  }
  
  #Store in the list
  adjusted_lakes[[j]] <- lake_data
  
  #Add the adjusted columns to the regular dataset
  assign(paste0(j), lake_data)
}



```


##Allometric Adjustments (Whole)
```{undefined eval=FALSE, include=FALSE}
#ALLOMETRIC ADJUSTMENTS
data.log <- dataclean %>%
  mutate_at(vars(sl, body_depth, ap_length_corrected, ap_width_corrected, jaw_length, ppl, ppw, dorsal_1, dorsal_2, dorsal_3, pelvic_spine, eye_diameter),
                  log10)

# size.coef is a function to get coefficient for #size adjustment #trait - name of trait col to get #slope coefficient
size.coef<-function(trait){
  ancova=lm(data=data.log, trait~sl+body_of_water)
  coef=ancova$coefficients[2]
  coef
}

#the following line produces slope coefficient. #Repeat for each trait.
BD.coef<-size.coef(data.log$body_depth)
APL.coef<-size.coef(data.log$ap_length_corrected)
APW.coef<-size.coef(data.log$ap_width_corrected)
JL.coef<-size.coef(data.log$jaw_length)
PPL.coef<-size.coef(data.log$ppl)
PPW.coef<-size.coef(data.log$ppw)
D1.coef<-size.coef(data.log$dorsal_1) #log of 0 is infinity
D2.coef<-size.coef(data.log$dorsal_2)
D3.coef<-size.coef(data.log$dorsal_3)
PS.coef<-size.coef(data.log$pelvic_spine)
ED.coef<-size.coef(data.log$eye_diameter)

# following makes a matrix 1 x k matrix of slopes for each trait
Coef<-matrix(c(BD.coef, APL.coef, APW.coef,JL.coef, PPL.coef, PPW.coef, D1.coef, D2.coef, D3.coef, PS.coef, ED.coef),dimnames = list(c("body_depth", "ap_length", "ap_width", "jaw_length", "ppl", "ppw", "dorsal_1", "dorsal_2", "dorsal_3", "pelvic", "eye")))


# Adjusts trait value using formula: Xadj=Xi*(mean(sl)/SLi)^b
dataclean$body_depth.adj<-dataclean$body_depth*(mean(dataclean$sl)/dataclean$sl)^Coef["body_depth",]
dataclean$ap_length.adj<-dataclean$ap_length_corrected*(mean(dataclean$sl)/dataclean$sl)^Coef["ap_length",]
dataclean$ap_width.adj<-dataclean$ap_width_corrected*(mean(dataclean$sl)/dataclean$sl)^Coef["ap_width",]
dataclean$jaw_length.adj<-dataclean$jaw_length*(mean(dataclean$sl)/dataclean$sl)^Coef["jaw_length",]
dataclean$ppl.adj<-dataclean$ppl*(mean(dataclean$sl)/dataclean$sl)^Coef["ppl",]
dataclean$ppw.adj<-dataclean$ppw*(mean(dataclean$sl)/dataclean$sl)^Coef["ppw",]
dataclean$dorsal_1.adj<-dataclean$dorsal_1*(mean(dataclean$sl)/dataclean$sl)^Coef["dorsal_1",]
dataclean$dorsal_2.adj<-dataclean$dorsal_2*(mean(dataclean$sl)/dataclean$sl)^Coef["dorsal_2",]
dataclean$dorsal_3.adj<-dataclean$dorsal_3*(mean(dataclean$sl)/dataclean$sl)^Coef["dorsal_3",]
dataclean$pelvic_spine.adj<-dataclean$pelvic_spine*(mean(dataclean$sl)/dataclean$sl)^Coef["pelvic",]
dataclean$eye_diameter.adj<-dataclean$eye_diameter*(mean(dataclean$sl)/dataclean$sl)^Coef["eye",]






```


## Test For loop 1
```{undefined eval=FALSE, include=FALSE}
#This works! Data pronoun! .data[[]]
#Loop for one lake through traits (outliers)
for (i in numeric_traits) {
    print(ggplot(rouge, aes(x = sl, y = .data[[i]])) + geom_point(color = "red") + geom_text(aes(label = fish_id), color = "red"))
}

#Figure out how to loop lakes - make lakes a LIST  of full dfs not c of strings)
for (j in lakes) {
   print(ggplot(j, aes(x = sl, y = body_depth.adj)) + geom_point(color = "deeppink2") + geom_text(aes(label = fish_id), color = "deeppink2"))
}


#Figure out how to loop both (yay! remember to use lakes)
for (j in lakes) {
  for (i in numeric_traits) {
    print(ggplot(j, aes(x = sl, y = .data[[i]])) + geom_point(color = "cyan3") + geom_text(aes(label = fish_id), color = "cyan3"))
  }
}

#Figure out how to loop by colour 
# or maybe not
for (j in lakes) {
  print(ggplot(j, aes(x = sl, y = body_depth.adj)) + geom_point(color = .data[[j]]) + geom_text(aes(label = fish_id), color = "deeppink2"))
}


```

#Plotting
##Outliers
``` {r Outliers}
#Numerical outliers

for (j in names(lakes)) {
  lake <- lakes[[j]]
  lakecolour <- lakecolours[[j]]
  for (i in numeric_traits_nosl) {
    print(ggplot(lake, aes(x = sl, y = .data[[i]])) + 
            geom_point(color = lakecolour) + 
            geom_text(aes(label = fish_id), color = lakecolour) +
            labs(title = paste(j,i))
          )
  }
}


```

##Numerical Traits
```{r Numerical Traits}

#Trait/Time Period comparison (All lakes)
for (i in numeric_traits) {
    print(ggplot(dataclean, aes(x = body_of_water, y = .data[[i]], color = time_period, fill = body_of_water)) +
            geom_boxplot() +
            theme_minimal() +
            scale_fill_manual(values = lakecolours) +
            scale_color_discrete(name = "Time Period"))
}



#Trait/Year Comparison
for (j in names(lakes)) {
  lake <- lakes[[j]]
  lakecolour <- lakecolours[[j]]
  for (i in numeric_traits) {
    print(ggplot(lake, aes(x =  as.factor(year), y = .data[[i]], color = time_period)) +
            geom_boxplot(fill = lakecolour) + 
            theme_minimal() +  
            labs(title = j))
}}





# Trait/Time Period/Sex
for (j in names(sexylakes)) {
  lake <- sexylakes[[j]]
  lakecolour <- lakecolours[[j]]
  for (i in numeric_traits) {
    print(ggplot(lake, aes(x =  time_period, y = .data[[i]], color = sex)) +
            geom_boxplot(fill = lakecolour) + 
            theme_minimal() +  
            labs(title = j))
}}




#Trait/Sex/Year
for (j in names(sexylakes)) {
  lake <- sexylakes[[j]]
  lakecolour <- lakecolours[[j]]
  for (i in numeric_traits) {
    print(ggplot(lake, aes(x =  as.factor(year), y = .data[[i]], color = sex)) +
            geom_boxplot(fill = lakecolour) + 
            theme_minimal() +  
            labs(title = j))
}}



```

##Armor Arrangements
```{r Armor Arrangements}
#Histograms of most common arrangements of plates


#Armor/Time Period comparison
for (j in names(lakes)){
  lake <- lakes[[j]]
  lakecolour <- lakecolours[[j]]
  for (i in timeperiods){
    for(h in platearrangements) {
      print(ggplot(data = filter(lake, time_period == i), 
                   aes(x = .data[[h]])) +
              geom_histogram(stat = "count", fill = lakecolour) +
              labs(title = paste(j,i,h), 
                   x = "Plate Arrangement", y = "Count") +
              theme_minimal())
    }}}




#Armor/Year comparison
for (j in names(lakes)){
  lake <- lakes[[j]]
  lakecolour <- lakecolours[[j]]
  for (i in sort(unique(lake[["year"]]))){ #Thanks ChGPT for this line :(
    for(h in platearrangements) {
      print(ggplot(data = filter(lake, year == i), 
                   aes(x = .data[[h]])) +
              geom_histogram(stat = "count", fill = lakecolour) +
              labs(title = paste(j,i,h), 
                   x = "Plate Arrangement", y = "Count") +
              theme_minimal())
    }}}




#Armor/Time Period/Sex comparison
for (j in names(sexylakes)){
  lake <- sexylakes[[j]]
  lakecolour <- lakecolours[[j]]
  for (i in timeperiods){
    for(h in platearrangements) {
      for (k in sex){
      print(ggplot(data = filter(lake, time_period == i & sex == k ), 
                   aes(x = .data[[h]])) +
              geom_histogram(stat = "count", fill = lakecolour) +
              labs(title = paste(j,i,h,k), 
                   x = "Plate Arrangement", y = "Count") +
              theme_minimal())
      }}}}




#Armor/year/Sex comparison
for (j in names(sexylakes)){
  lake <- sexylakes[[j]]
  lakecolour <- lakecolours[[j]]
  for (i in sort(unique(lake[["year"]]))) {
    for(h in platearrangements) {
      for (k in sex){
      print(ggplot(data = filter(lake, year == i & sex == k ), 
                   aes(x = .data[[h]])) +
              geom_histogram(stat = "count", fill = lakecolour) +
              labs(title = paste(j,i,h,k), 
                   x = "Plate Arrangement", y = "Count") +
              theme_minimal())
    }}}}

```


##Presence/Absence
```{r Presence/Absence}

#Pres/abs Historical/Present
for (j in names(lakes)) {
  lake <- lakes[[j]]
  for (i in countable_traits) {
    print(ggplot(data = lake, aes(x =  time_period, fill = .data[[i]])) +
            geom_bar(stat = "count", position = "fill") +
            labs(title = paste(j,i), 
       x = "Time Period", y = "Proportion of Fish") +
         theme_minimal() +
         scale_fill_manual(name = "Presence", values = presabscolours))
  }}



#Years
for (j in names(lakes)) {
  lake <- lakes[[j]]
  for (i in countable_traits) {
    print(ggplot(data = lake, aes(x =  as.factor(year), fill = .data[[i]])) +
            geom_bar(stat = "count", position = "fill") +
            labs(title = paste(j,i), 
       x = "Year", y = "Proportion of Fish") +
         theme_minimal() +
         scale_fill_manual(name = "Presence", values = presabscolours))
  }}




#Countable Traits/Time Period/Sex
for (j in names(sexylakes)) {
  lake <- sexylakes[[j]]
  for (i in countable_traits) {
    for (k in timeperiods) {
    print(ggplot(data = filter(lake, time_period == k), aes(x =  sex, fill = .data[[i]])) +
            geom_bar(stat = "count", position = "fill") +
            labs(title = paste(j,i,k), 
       x = "Sex", y = "Proportion of Fish") +
         theme_minimal() +
         scale_fill_manual(name = "Presence", values = presabscolours))
  }}}




#Countable Traits/Years/Sex
for (j in names(sexylakes)) {
  lake <- sexylakes[[j]]
  for (i in countable_traits) {
    for (k in sort(unique(lake[["year"]]))) {
    print(ggplot(data = filter(lake, year == k), aes(x =  sex, fill = .data[[i]])) +
            geom_bar(stat = "count", position = "fill") +
            labs(title = paste(j,i,k), 
       x = "Sex", y = "Proportion of Fish") +
         theme_minimal() +
         scale_fill_manual(name = "Presence", values = presabscolours))
  }}}

```




#Export clean data NOT READY YET
```{r eval=FALSE, include=FALSE}
write.csv(dataclean, "../Data/data.clean.csv")
```


#PCA of defensive traits NOT READY YET
```{r eval=FALSE, include=FALSE}
trait_def <- c("ap_length.adj", "ap_width.adj", "ppl.adj", "ppw.adj", 
               "dorsal_1.adj", "dorsal_2.adj", "pelvic_spine.adj", "plate_lr_total")  

pca.for <- prcomp(dataclean[, trait_def], scale. = TRUE)  
pc_scores.for <- as.data.frame(pca.for$x)
summary(pca.for)
```


# Other NOT READY YET
```{r T test loop + pool check, eval=FALSE, include=FALSE}
# Empty list to store models
Q1.models <- list()

# Loop through traits and fit GLMs
for (trait in traits.cont) {
  formula <- as.formula(paste(trait, "~ Sex + Drought"))
  Q1.models[[trait]] <- glm(formula, family = gaussian(link = "identity"), data = dat1)
}

for (trait in traits.cont) {
  cat("\n### Summary for:", trait, "###\n")
  print(summary(Q1.models[[trait]]))
}


###


dat_sub<- data %>%
  filter(year %in% c(2007,2012,2013))

dat_sub$year <- factor(dat_sub$year, levels = c("2007", "2012", "2013"))
dat_sub$LP_No <- as.numeric(dat_sub$LP_No)
mod.LP <- glm(LP_No ~ Sex + year, family = poisson, data = dat_sub)
summary(mod.LP)

planned_contrasts <- list(
  "2007 vs 2012" = c(-1, 1, 0),
  "2012 vs 2013" = c(0, -1, 1),
  "2007 vs 2013" = c(-1, 0, 1)
)
# Perform emmeans for the 'pop' variable
emm <- emmeans(mod.LP, ~ year)

# Run the planned contrasts
planned_results <- contrast(emm, method = planned_contrasts)

# View the results
summary(planned_results)

```

